name: build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.6.0"

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Build folders for npm
        run: |
          npm run build
        env:
          CI: true

      - name: NPM Publish Main
        if: github.ref == 'refs/heads/main'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
          access: "public"

      - name: NPM Publish Develop
        if: github.ref == 'refs/heads/develop'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{secrets.NPM_TOKEN}}
          tag: "develop"
          access: "public"

  slack:
    runs-on: [self-hosted, linux]
    needs: [build] # Include all jobs that should be in message
    steps:
      - name: Checkout Figure shared actions
        uses: actions/checkout@v3
        with:
          repository: FigureTechnologies/shared-actions
          ref: v1
          token: ${{ secrets.PAT }}
          path: shared-actions

      - uses: ./shared-actions/slack-notification
        with:
          emoji: ":snowboarder:"
          channel: walletconnect-js
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_needs_context: ${{ toJSON(needs) }}
